#!/bin/bash
# Health App - Quick Reference Commands
# Run this file to see all available commands
# Or copy/paste individual commands as needed

echo "🏥 Afya Yako AI - Quick Reference Commands"
echo "=========================================="
echo ""

echo "📦 SETUP & INSTALLATION"
echo "----------------------"
echo "1. Create virtual environment:"
echo "   python -m venv venv"
echo ""
echo "2. Activate virtual environment:"
echo "   source venv/bin/activate  # Linux/Mac"
echo "   venv\\Scripts\\activate  # Windows"
echo ""
echo "3. Install dependencies:"
echo "   pip install -r requirements.txt"
echo ""

echo "🗄️ DATABASE SETUP"
echo "----------------"
echo "1. Create migrations:"
echo "   python manage.py makemigrations"
echo ""
echo "2. Apply migrations:"
echo "   python manage.py migrate"
echo ""
echo "3. Create admin user:"
echo "   python manage.py createsuperuser"
echo ""
echo "4. Reset database (dev only):"
echo "   python manage.py flush"
echo "   python manage.py migrate"
echo ""

echo "🚀 RUN APPLICATION"
echo "-------------------"
echo "1. Start development server:"
echo "   python manage.py runserver"
echo ""
echo "2. Start on specific port:"
echo "   python manage.py runserver 8080"
echo ""
echo "3. Access dashboard:"
echo "   http://localhost:8000/accounts/dashboard/"
echo ""
echo "4. Access admin panel:"
echo "   http://localhost:8000/admin/"
echo ""
echo "5. Access chat:"
echo "   http://localhost:8000/chat-ai/"
echo ""

echo "📊 API TESTING"
echo "---------------"
echo "1. Health Vitals:"
echo "   curl -X GET http://localhost:8000/api/vitals/"
echo ""
echo "2. Log Meal:"
echo "   curl -X POST http://localhost:8000/api/nutrition/ \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{\"meal_type\": \"BREAKFAST\", \"calories\": 350}'"
echo ""
echo "3. Get Health Summary:"
echo "   curl http://localhost:8000/chat-ai/api/health-summary/"
echo ""
echo "4. Get Nutrition Advice:"
echo "   curl http://localhost:8000/chat-ai/api/nutrition-advice/"
echo ""

echo "📝 MANAGEMENT COMMANDS"
echo "---------------------"
echo "1. Create superuser:"
echo "   python manage.py createsuperuser"
echo ""
echo "2. Check migrations:"
echo "   python manage.py showmigrations"
echo ""
echo "3. Make migrations:"
echo "   python manage.py makemigrations [app_name]"
echo ""
echo "4. Migrate specific app:"
echo "   python manage.py migrate accounts"
echo ""
echo "5. Run Django shell:"
echo "   python manage.py shell"
echo ""
echo "6. Load fixture data:"
echo "   python manage.py loaddata fixture.json"
echo ""

echo "🧪 TESTING"
echo "----------"
echo "1. Run all tests:"
echo "   python manage.py test"
echo ""
echo "2. Run specific app tests:"
echo "   python manage.py test accounts"
echo ""
echo "3. Run specific test class:"
echo "   python manage.py test accounts.tests.HealthVitalTest"
echo ""

echo "🔧 DEVELOPMENT UTILITIES"
echo "------------------------"
echo "1. Freeze requirements:"
echo "   pip freeze > requirements.txt"
echo ""
echo "2. Install from requirements:"
echo "   pip install -r requirements.txt"
echo ""
echo "3. Check Django version:"
echo "   python -m django --version"
echo ""
echo "4. Collect static files:"
echo "   python manage.py collectstatic"
echo ""

echo "📚 DOCUMENTATION QUICK LINKS"
echo "----------------------------"
echo "1. Project Overview:"
echo "   cat README.md"
echo ""
echo "2. API Documentation:"
echo "   cat API_DOCUMENTATION.md"
echo ""
echo "3. Implementation Guide:"
echo "   cat IMPLEMENTATION_GUIDE.md"
echo ""
echo "4. Setup Summary:"
echo "   cat SETUP_SUMMARY.md"
echo ""
echo "5. Compliance & Safety:"
echo "   cat compliance_safety.py"
echo ""

echo "🐛 DEBUGGING"
echo "------------"
echo "1. Django shell (interactive):"
echo "   python manage.py shell"
echo ""
echo "2. Python code:"
echo "   >>> from accounts.models import HealthVital"
echo "   >>> HealthVital.objects.all()"
echo "   >>> from accounts.health_ai_engine import get_health_summary"
echo ""
echo "3. Check logs (if enabled):"
echo "   tail -f logs/debug.log"
echo ""

echo "🌐 DEPLOYMENT"
echo "--------------"
echo "1. Production settings:"
echo "   - Set DEBUG = False"
echo "   - Configure ALLOWED_HOSTS"
echo "   - Set SECRET_KEY from environment"
echo "   - Use PostgreSQL/MySQL"
echo "   - Enable HTTPS"
echo ""
echo "2. Environment variables needed:"
echo "   SECRET_KEY=your-secret-key"
echo "   DEBUG=False"
echo "   GOOGLE_API_KEY=your-gemini-api-key"
echo "   DATABASE_URL=postgresql://user:password@host/db"
echo ""

echo "📱 COMMON WORKFLOWS"
echo "-------------------"
echo ""
echo "WORKFLOW 1: Create & Test New Feature"
echo "1. python manage.py makemigrations"
echo "2. python manage.py migrate"
echo "3. python manage.py runserver"
echo "4. Test via API or admin panel"
echo ""

echo "WORKFLOW 2: Add New API Endpoint"
echo "1. Add model in accounts/models.py"
echo "2. Create serializer in accounts/serializers.py"
echo "3. Create ViewSet in accounts/views.py"
echo "4. Register route in accounts/urls.py"
echo "5. Create migration & migrate"
echo ""

echo "WORKFLOW 3: Deploy to Production"
echo "1. Prepare environment"
echo "2. Set environment variables"
echo "3. Collect static files: python manage.py collectstatic"
echo "4. Run migrations on server"
echo "5. Start Gunicorn/uWSGI server"
echo "6. Configure Nginx/Apache"
echo ""

echo "🆘 TROUBLESHOOTING"
echo "------------------"
echo ""
echo "Issue: ModuleNotFoundError"
echo "Solution: pip install -r requirements.txt"
echo ""
echo "Issue: DatabaseError on migrate"
echo "Solution: python manage.py flush && python manage.py migrate"
echo ""
echo "Issue: Static files not loading"
echo "Solution: python manage.py collectstatic"
echo ""
echo "Issue: Admin panel inaccessible"
echo "Solution: Create superuser with createsuperuser"
echo ""
echo "Issue: API returns 401"
echo "Solution: Check authentication headers or user permissions"
echo ""

echo "✅ VERIFICATION CHECKLIST"
echo "-------------------------"
echo "□ Virtual environment activated"
echo "□ Dependencies installed (pip install -r requirements.txt)"
echo "□ Database migrated (python manage.py migrate)"
echo "□ Superuser created"
echo "□ Development server running"
echo "□ Dashboard accessible at localhost:8000"
echo "□ Admin panel accessible at localhost:8000/admin"
echo "□ API endpoints working"
echo "□ AI features generating recommendations"
echo ""

echo "🎯 NEXT STEPS"
echo "-------------"
echo "1. Complete Setup:"
echo "   python manage.py makemigrations"
echo "   python manage.py migrate"
echo "   python manage.py createsuperuser"
echo ""
echo "2. Start Server:"
echo "   python manage.py runserver"
echo ""
echo "3. Create Test Data:"
echo "   - Visit http://localhost:8000/admin/"
echo "   - Add test users and health data"
echo ""
echo "4. Test API:"
echo "   - Use curl, Postman, or Thunder Client"
echo "   - Test endpoints from API_DOCUMENTATION.md"
echo ""
echo "5. Customize:"
echo "   - Update dashboard templates"
echo "   - Add more AI features"
echo "   - Implement frontend"
echo ""

echo "=========================================="
echo "For detailed info, see README.md & documentation"
echo "=========================================="
