# Generated by Django 6.0.1 on 2026-01-30 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('pattern', 'Pattern'), ('daily_guidance', 'Daily Guidance'), ('alert', 'Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MenstrualProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_start', models.DateField(help_text='Day 1 of the last menstrual period')),
                ('avg_cycle_length', models.IntegerField(default=28, help_text='Average cycle length in days')),
                ('avg_period_length', models.IntegerField(default=5, help_text='Average bleeding duration in days')),
                ('pregnancy_goal', models.CharField(choices=[('avoid', 'Avoid Pregnancy'), ('conceive', 'Trying to Conceive'), ('track', 'Just Tracking')], default='track', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Menstrual Profile',
                'verbose_name_plural': 'Menstrual Profiles',
            },
        ),
        migrations.CreateModel(
            name='CycleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cycle_day_number', models.IntegerField(help_text='Day 1-N of cycle')),
                ('phase', models.CharField(choices=[('menstrual', 'Menstrual'), ('follicular', 'Follicular'), ('ovulation', 'Ovulation'), ('luteal', 'Luteal')], max_length=15)),
                ('fertility_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bleeding_level', models.CharField(choices=[('none', 'None'), ('spotting', 'Spotting'), ('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='none', max_length=10)),
                ('pain_score', models.IntegerField(default=0, help_text='0-5 scale')),
                ('mood', models.CharField(blank=True, choices=[('great', 'Great'), ('good', 'Good'), ('neutral', 'Neutral'), ('low', 'Low'), ('sad', 'Sad')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('symptoms', models.JSONField(default=list, help_text='List of symptoms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstrual_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
