# Generated by Django 6.0.1 on 2026-01-30 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_childprofile_healthvital_medicalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodSugarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar_mg_dl', models.IntegerField()),
                ('measurement_time', models.CharField(choices=[('FASTING', 'Fasting (before meal)'), ('POSTPRANDIAL', 'Post-prandial (after meal)'), ('BEDTIME', 'Bedtime'), ('RANDOM', 'Random')], max_length=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_sugar_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyNutritionGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_calories', models.IntegerField(default=2000)),
                ('target_protein_g', models.IntegerField(default=50)),
                ('target_carbs_g', models.IntegerField(default=300)),
                ('target_fat_g', models.IntegerField(default=65)),
                ('target_fiber_g', models.IntegerField(default=25)),
                ('target_water_ml', models.IntegerField(default=2000)),
                ('special_diet', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_type', models.CharField(max_length=100)),
                ('intensity', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('VERY_HIGH', 'Very High')], max_length=10)),
                ('duration_minutes', models.IntegerField()),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='FitnessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_steps_daily', models.IntegerField(default=10000)),
                ('target_exercise_minutes_weekly', models.IntegerField(default=150)),
                ('target_workouts_weekly', models.IntegerField(default=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(auto_now_add=True)),
                ('avg_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('avg_blood_pressure', models.CharField(blank=True, max_length=10)),
                ('avg_heart_rate', models.IntegerField(blank=True, null=True)),
                ('avg_blood_sugar', models.IntegerField(blank=True, null=True)),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('total_exercise_minutes', models.IntegerField(blank=True, null=True)),
                ('total_steps', models.IntegerField(blank=True, null=True)),
                ('avg_mood_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('avg_sleep_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('health_risks', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=100)),
                ('clinic_name', models.CharField(max_length=100)),
                ('appointment_date', models.DateTimeField()),
                ('reason', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date'],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('ONCE_DAILY', 'Once daily'), ('TWICE_DAILY', 'Twice daily'), ('THRICE_DAILY', 'Three times daily'), ('FOUR_TIMES_DAILY', 'Four times daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('AS_NEEDED', 'As needed')], max_length=20)),
                ('reason', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('side_effects', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicationReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='accounts.medication')),
            ],
        ),
        migrations.CreateModel(
            name='MindfulnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('MEDITATION', 'Meditation'), ('BREATHING', 'Breathing Exercise'), ('YOGA', 'Yoga'), ('STRETCHING', 'Stretching'), ('JOURNALING', 'Journaling')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('feeling_before', models.CharField(blank=True, max_length=100)),
                ('feeling_after', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindfulness_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('EXCELLENT', 'Excellent 😄'), ('GOOD', 'Good 😊'), ('NEUTRAL', 'Neutral 😐'), ('POOR', 'Poor 😞'), ('VERY_POOR', 'Very Poor 😢')], max_length=10)),
                ('triggers', models.CharField(blank=True, max_length=200)),
                ('anxiety_level', models.IntegerField(default=0, help_text='0-10 scale')),
                ('stress_level', models.IntegerField(default=0, help_text='0-10 scale')),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('food_items', models.TextField()),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('protein_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbs_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fat_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fiber_g', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep_duration_hours', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sleep_quality', models.IntegerField(default=5, help_text='1-10 scale')),
                ('bed_time', models.TimeField()),
                ('wake_time', models.TimeField()),
                ('recorded_date', models.DateField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('amount_ml', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='DailySteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField(auto_now_add=True, db_index=True)),
                ('steps', models.IntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_steps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_date'],
                'unique_together': {('user', 'recorded_date')},
            },
        ),
        migrations.CreateModel(
            name='MedicationAdherence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('was_taken', models.BooleanField()),
                ('time_taken', models.TimeField(blank=True, null=True)),
                ('skipped_reason', models.CharField(blank=True, max_length=200)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adherence', to='accounts.medication')),
            ],
            options={
                'ordering': ['-scheduled_date'],
                'unique_together': {('medication', 'scheduled_date')},
            },
        ),
    ]
